### ISSUE TITLE
Show "$" instead of "USD"

### ISSUE THREAD

**Issue by xsorifc28** [jalibu/MMM-Jast#14]
Great codebase, very organized!
The module is very useful as well.

Is this possible to configure? I'd like to see:
 `TICKER $XX.XX (+$XX.XX)` 
instead of :
`TICKER XX.XX USD (+XX.XX USD)`

**Comment by jalibu** [comment]
Hi @xsorifc28
I'll add this to the next release. With a little luck, this week.

**Comment by jalibu** [comment]
Hey @xsorifc28 please check out the latest release

**Comment by xsorifc28** [comment]
Looks and works great, thanks again.
