### ISSUE TITLE
How to set the request timeout

### ISSUE THREAD

**Issue by liqiang1304** [jalibu/MMM-Jast#15]
Hi~

The internet connection from China to Yahoo Server is not stable. 
How can I change the timeout, or auto retry after timeout?

thanks

`[24.04.2021 03:36.52.980] [ERROR] There was an error requesting the API. request
 to https://query2.finance.yahoo.com/v10/finance/quoteSummary/SAP.DE?formatted=f
alse&modules=price%2CsummaryDetail failed, reason: read ETIMEDOUT                `

**Comment by jalibu** [comment]
Hmm... The module uses the node-yahoo-finance2 module. It's doc mentions a possibility to pass some options to the fetch: https://github.com/gadicc/node-yahoo-finance2/tree/devel/docs

Please feel free to contribute with a PR.
