### ISSUE TITLE
Scrolls only on half screen

### ISSUE THREAD

**Issue by websterjazz** [jalibu/MMM-Jast#17]
Platform (Hardware/OS): raspberry Pi 4

Node version: 14.17.0

MagicMirror version: 2.15.0

Module version: 2.1.0

Description of the issue: Doesn't scroll from screen end to end. Starts from the middle of the screen. I've selected the horizontal option and would like the ticker to start from the right end of the screen and scroll all the alway till the left end. 
I have set the position as bottom bar.
My config code is 
  ```
{
	module: "MMM-Jast",
	position: "bottom_bar",
	config: {
		maxWidth: "100%",
		updateIntervalInSeconds: 300,
		fadeSpeedInSeconds: 20, // Higher value: vertical -> faster // horizontal -> slower
		scroll: "horizontal", // One of ["none", "vertical", "horizontal"]
		useGrouping: false,
		currencyStyle: "symbol", // One of ["code", "symbol", "name"]
		showColors: true,
		showCurrency: true,
		showChangePercent: true,
		showChangeValue: false,
		showChangeValueCurrency: false,
		showDepot: false,
		showDepotGrowthPercent: false,
		showDepotGrowth: false,
		numberDecimalsValues: 2,
		numberDecimalsPercentages: 1,
		stocks: [
			{ name: "BASF", symbol: "BAS.DE", quantity: 10 },
			{ name: "SAP", symbol: "SAP.DE", quantity: 15 },
			{ name: "Henkel", symbol: "HEN3.DE" },
			{ name: "Alibaba", symbol: "BABA"}
		]
	  }
    }, 
```

Observations after some more R&D:
When screen orientation is set to vertical. The scroll happens from screen end to end . That's what I want .
But when the screen/monitor orientation is horizontal then the scrolling happens from centre of screen to left .

**Comment by jalibu** [comment]
Hi @websterjazz

what‘s your screen resolution?

**Comment by websterjazz** [comment]
1920x1080! [IMG_20210604_195823.jpg] (https://user-images.githubusercontent.com/16868016/120817399-4daa9a00-c56f-11eb-8fe9-33227f529192.jpg)

**Comment by jalibu** [comment]
I can reproduce the issue

**Comment by websterjazz** [comment]
@jalibu I am sorry I don't understand

**Comment by jalibu** [comment]
I can reproduce/verify this issue on my system. I‘ll fix it soon

**Comment by jalibu** [comment]
Hi @websterjazz,

this issue occurs when there are not enough stocks in the list to "fill" the row. The easiest workaround would be to double/tribble the entries in the stocks list:

  	```
stocks: [
  		{ name: "BASF", symbol: "BAS.DE", quantity: 10 },
  		{ name: "SAP", symbol: "SAP.DE", quantity: 15 },
  		{ name: "Henkel", symbol: "HEN3.DE" },
  		{ name: "Alibaba", symbol: "BABA"},
  		{ name: "BASF", symbol: "BAS.DE"},
  		{ name: "SAP", symbol: "SAP.DE"},
  		{ name: "Henkel", symbol: "HEN3.DE" },
  		{ name: "Alibaba", symbol: "BABA"},
		{ name: "BASF", symbol: "BAS.DE"},
  		{ name: "SAP", symbol: "SAP.DE"},
  		{ name: "Henkel", symbol: "HEN3.DE" },
  		{ name: "Alibaba", symbol: "BABA"},
  	]
```

**Comment by websterjazz** [comment]
@jalibu .. ok I was just working with default options... Let me try adding more stocks and I'll update you .
P.S - I don't deal in stocks at all 😆.. it's just that I found this module of yours pretty awesome ..so want to have it on my mirror.

**Comment by jalibu** [comment]
Hey @websterjazz,
I added a virtual multiplier with the latest release. Please check it out.

Thank you for your feedback

**Comment by websterjazz** [comment]
@jalibu I did that..added a few more stocks and it works like a charm now... Thank you :)
