### ISSUE TITLE
Deleted stock symbols appearing

### ISSUE THREAD

**Issue by vballnut** [jalibu/MMM-Jast#18]
Platform (Hardware/OS): Raspberry Pi / Raspian Buster

Node version: 10.24.1

MagicMirror version: 2.14

Module version:  latest

Description of the issue: I recently updated the MMM-Jast stocks list I had running with a completely new list.  When I restarted MagicMirror, both lists now display.  My MagicMirror is actually set up as a Magic monitor with MMM-Pages rotating the various modules, with MMM-Jast being 1 of them.  During the rotation, when it gets to the MMM-Jast page, MMM-Jast module cycles through 2 "pages" showing the old, then the new, stocks.  I've done a git pull to make sure I have the latest version (no update occurred), along with npm install.  I've also tried deleting all the stocks in the list except 1, but it still shows the old list (and the new single stock on a separate page).  Is there a cache I need to clear?

UPDATE: I changed the zoom level to a smaller one and now it only shows the old list.

UPDATE2: I rearranged MMM-Jast to different positions under MMM-Pages and it actually displays differently.  In one position, it displays a combination of the old and new list like I mentioned above, in another position it shows only the old list, while another position shows only the new list, but after awhile switches to the old list.  The position that seems to show it longest is the 2nd one.

**Comment by vballnut** [comment]
After sitting for several hours, it has corrected itself so there must be some caching going on.  Sorry for the false issue :-)

**Comment by jalibu** [comment]
Could you please attach your config.js here?

There is no cache.

**Comment by vballnut** [comment]
> Could you please attach your config.js here?
> 
> There is no cache.

[MMM-Jast config.txt](https://github.com/jalibu/MMM-Jast/files/6604552/MMM-Jast.config.txt)

**Comment by jalibu** [comment]
I still have no idea how this could happen. You are sure that there is only one module instance in the config?

**Comment by vballnut** [comment]
> I still have no idea how this could happen. You are sure that there is only one module instance in the config?

I can't find it either, but it's occurring less and less now that it's been active this long.  Sounds like whatever created the issue is slowly correcting itself... nothing like a bug crawling into a crack in the wall... hate those!

**Comment by jalibu** [comment]
You did not restart the MagicMirror after you have changed the config?!

**Comment by vballnut** [comment]
> You did not restart the MagicMirror after you have changed the config?!

 I restart every time I change the config. What I meant was running this long since the last change to the config (over a week now). Wherever it was cached, it seems to have released it now. I didn’t see the old list all day yesterday.

**Comment by jalibu** [comment]
hmm... ok. Please reopen, if you're facing this problem again. I still have no idea how this could happen
