### ISSUE TITLE
Copied and pasted your code..."Undefined"

### ISSUE THREAD

**Issue by lukepetrula** [jalibu/MMM-Jast#19]
Platform (Hardware/OS):Raspberry Pi OS

Node version:

MagicMirror version: 2.15

Module version:

Description of the issue: Undefined Error

Copied and pasted your code, only displays "undefined". Any ideas?

**Comment by jalibu** [comment]
What does the log say?
Did you run *npm install* from the right folder?
Where does undefined error display?

**Comment by lukepetrula** [comment]
I currently see nothing in logs that would suggest the module is failing. But yes its installed in my modules folder. And the "undefined" is what is displayed when I run my mirror.

**Comment by lukepetrula** [comment]
I lied, I'm getting a "deprecationwarning" "due to security and usability issues"

**Comment by jalibu** [comment]
Where/when do you get this error?

**Comment by jalibu** [comment]
Hi @lukepetrula,

Please give me exact step-by-step instructions on how to reproduce this error.

Thank you for your support

**Comment by jalibu** [comment]
@lukepetrula please re-open with instructions, if the problem still exists.

**Comment by jacklu333333** [comment]
Hi, I have the same error.
This is my error, how can I fix it?
```
[20.08.2021 00:18.33.362] [ERROR] (node:18369) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```
Thanks

**Comment by jalibu** [comment]
Hi @jacklu333333 
I think the deprecation warning does not cause any problems. You'll get an "undefined" error, if you have invalid symbols in your stock list.
Please check them. Please note, that they are case sensitive!

**Comment by jalibu** [comment]
@jacklu333333 wait... I can reproduce a problem... I'll come back to this issue when I fixed it

**Comment by jalibu** [comment]
Nope, I can not reproduce any issue. Please pull the latest version

**Comment by jacklu333333** [comment]
Alright, thanks for your help.
I do use the latest version `MMM-Jast` with the sample configuration in the ReadMe.

Other Configuration:
```
Pi Version: Pi4
OS Version: 2021-05-07-raspios-buster-arm64
MagicMirror2 version: v2.16.0
```
It probably occurs due to some other configuration. If I find out, I will share it.

**Comment by jalibu** [comment]
are there any errors in the console log? @jacklu333333

**Comment by jacklu333333** [comment]
@jalibu 
That's the only Error log in my output.
```
[20.08.2021 16:18.32.068] [ERROR] (node:12203) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```
But I do agree with you that is not the reason the error occurs because I saw the undefined way before the error log pop up this time.

**Comment by jalibu** [comment]
@jacklu333333 can you open the Browser Console log?
It's CTRL + Shift + i on RaspberryOS and then refresh the page mit CTRL + r

**Comment by jacklu333333** [comment]
Yes, the error pops up. I think it is the problem of npm packages

```
module.js:94 Template render error: (templates/MMM-Jast.njk)
  RangeError: Incorrect locale information provided
    at Object.n.t (http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js:2:2630)
    at http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js:2:37878
    at eval (eval at i.B (http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js:2:38482), <anonymous>:22:11)
    at http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js:2:38236
    at n.root [as rootRenderFunc] (eval at i.B (http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js:2:38482), <anonymous>:264:3)
    at n.i.getExported (http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js:2:38192)
    at eval (eval at i.B (http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js:2:38482), <anonymous>:21:5)
    at n.i.getTemplate (http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js:2:35207)
    at eval (eval at i.B (http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js:2:38482), <anonymous>:19:5)
    at http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js:2:38246
(anonymous) @ module.js:94
```

**Comment by jalibu** [comment]
There you have your problem ;-)
`Incorrect locale information provided`

Check locale in config.js and fix it :-)

**Comment by jacklu333333** [comment]
Thanks a lot and sorry for such kind of error.
In my configuration, I misconfig `en-US` as `en_US`.
