### ISSUE TITLE
MMM-Jast fails to display Australian ETF's

### ISSUE THREAD

**Issue by svengali1** [jalibu/MMM-Jast#20]
Platform (Hardware/OS): Raspberry Pi OS

Node version:

MagicMirror version: V2.15.0

Module version:

Description of the issue:  MMM-Jast fails to display Australian (ASX) ETF prices.

Using latest MMM-Jast

Can successfully pull single Australian stocks (e.g AfterPay "APT.AX" displays correctly) can also pull AUD/USD ("AUDUSD=X") and the ASX200 ("^AXJO") however fails to display data for Australian ETFS (specifically ETHI & VDHG "ETHI.AX" "VDHG.AX")

Successfully pulls American ETF prices (trialled two different ones)

I see an Error in terminal (however doesn't seem to have any effect on module function?)

[21.06.2021 11:19.48.414] [ERROR] Failed to fetch git data for MMM-Jast: Error: block timeout reached

Config is as follows:

		  {
				module: "MMM-Jast",
				position: "top_left",
					config: {
						maxWidth: "100%",
						updateIntervalInSeconds: 300,
						fadeSpeedInSeconds: 3.5, // Higher value: vertical -> faster // horizontal -> slower
						scroll: "none", // One of ["none", "vertical", "horizontal"]
						useGrouping: false,
						currencyStyle: "code", // One of ["code", "symbol", "name"]
						showColors: true,
						showCurrency: true,
						showChangePercent: true,
						showChangeValue: false,
						showChangeValueCurrency: false,
						showDepot: false,
						showDepotGrowthPercent: false,
						showDepotGrowth: false,
						numberDecimalsValues: 2,
						numberDecimalsPercentages: 1,
						virtualHorizontalMultiplier: 2,
							stocks: [
								{ name: "AUD/USD", symbol: "AUDUSD=X", },
								{ name: "ASX200", symbol: "^AXJO", },
								{ name: "ETHI-ETF", symbol: "ETHI.AX" },
								{ name: "VDHG-ETF", symbol: "VDHG.AX" }, 
								{ name: "AfterPay", symbol: "APT.AX" },
								{ name: "VUG-ETF", symbol: "VUG" } 
						}
		},

(Fails to display ETHI-ETF & VDHG-ETF however displays VUG-ETF)

doesn't seem to produce an error as it does when symbols are wrong. I think its probably returning something, however its something that MMM-Jast is not prepared for?

This is about my extent of trouble shooting & programming skills.

Interested to see if you can suggest a fix.

**Comment by svengali1** [comment]
NOTE - i removed the , after "AUDUSD=X" and "^AXJO" in my config and tried again. still fails to display.

I'd previously been trialling quantity for showDepot & showDepotGrowth however removed this field while trying to trouble shoot the issue with not displaying Australian ETF's.

**Comment by jalibu** [comment]
There is a missing ] at the end of your stock list

**Comment by jalibu** [comment]
I found the problem.
The API did not return an object that is necessary to display the currency. However, I can get the currency from another object, which seems to be provided more reliably by the API.

Please checkout the latest v2.4.2

**Comment by svengali1** [comment]
Legend. Works like a charm now, thanks for the prompt response and update.

Great module btw, particularly like the 'Depot' functions - this plus the stock price ticker replaces my need to log into my share trading platform.
