### ISSUE TITLE
How to add a header

### ISSUE THREAD

**Issue by soubhik-khan** [jalibu/MMM-Jast#21]
I'm using the static config. it will be great to have header included to match the default module theme! I would like to add a header something like "Stocks". and a horizontal line and then the stock prices. 
I'm not an expert in Java, so finding it little difficult to follow! I was hoping to add it in the MMM-Jast.js file, something like https://github.com/TeraTech/MMM-WiFiPassword/blob/master/MMM-WiFiPassword.js#L53. 
But MMM-Jast.js format looks little different! Will appreciate some help here..

**Comment by jalibu** [comment]
Hi @soubhik-khan,

you don't have to change any code to add a header to the module. Just add a "header" property into the module specification in the config.js file.

```
{
	module: "MMM-Jast",
	position: "top_left",
	header: "This is your header",
	config: {
		blabla...
	}
}
```

**Comment by soubhik-khan** [comment]
> Hi @soubhik-khan,
> 
> you don't have to change any code to add a header to the module. Just add a "header" property into the module specification in the config.js file.
> 
> ```
> {
> 	module: "MMM-Jast",
> 	position: "top_left",
> 	header: "This is your header",
> 	config: {
> 		blabla...
> 	}
> }
> ```

awesome! thank you so much!

**Comment by jalibu** [comment]
You're welcome
