### ISSUE TITLE
Issue with the 'Quantity' field under stock object 

### ISSUE THREAD

**Issue by tmartinez28** [jalibu/MMM-Jast#23]
Platform (Hardware/OS):

Magicmirror 

MagicMirror version:

magicmirror:v2.15.0

Module version:

v2.4.3

Description of the issue:  Under stock object, for the 'quantity' field, it takes an integer as an input, however with more and more stock apps including features such as 'fractional shares' is there any possible way to change it to a decimal so I can input my fractional shares?  ex. owning .5 of an amazon share 

Also wanted to say loving the module so far! only issue I have other than this is the vertical scrolling bug mentioned in another bug

**Comment by jalibu** [comment]
hi @tmartinez28 
it should also work with decimals. please check and give me feedback. I think there is only an inaccuracy in the readme.

**Comment by jalibu** [comment]
@tmartinez28 issue solved?

**Comment by jalibu** [comment]
please reopen, if problem still exists
