### ISSUE TITLE
High CPU consumption 

### ISSUE THREAD

**Issue by goldyfruit** [jalibu/MMM-Jast#35]
### Platform

Raspberry Pi OS Bullseye 64-bit

### Node.js Version

16.13.1

### MagicMirror Version

2.18.0

### Module Version

8fd21f0e5a5f6f22b2f419d894747a3ea4cfac61

### Description

When the module is enabled, the CPU consumption almost double, MagicMirror is running within a Docker container with OpenGL acceleration.

### Possible solution

Does the `fadeSpeedInSeconds` option could be the culprit?

### Steps to reproduce

1. Apply my module configuration
2. Restart the MagicMirror

### config.js

```javascript
{
	module: "MMM-Jast",
	disable: true,
	position: "bottom_bar",
	config: {
		maxWidth: "100%",
		updateIntervalInSeconds: 300,
		fadeSpeedInSeconds: 25,
		scroll: "horizontal", // One of ["none", "vertical", "horizontal"]
		useGrouping: false,
		currencyStyle: "code", // One of ["code", "symbol", "name"]
		lastUpdateFormat: "HH:mm",
		showColors: true,
		showCurrency: true,
		showChangePercent: true,
		showChangeValue: false,
		showChangeValueCurrency: false,
		showLastUpdate: false,
		showPortfolioValue: false,
		showPortfolioGrowthPercent: false,
		showPortfolioGrowth: false,
		numberDecimalsValues: 2,
		numberDecimalsPercentages: 1,
		virtualHorizontalMultiplier: 2,
		stocks: [
			{ name: "SYM0", symbol: "SYM0", quantity: 50 },
			{ name: "SYM2", symbol: "SYM1", quantity: 200 },
			{ name: "SYM2", symbol: "SYM2", quantity: 266 }
		]
	}
},
```

**Comment by jalibu** [comment]
Hi @goldyfruit, the module uses CSS Keyframe animations for fading. The other backend components should be really economical with computing resources.
Is your browser also running in the container or just the server parts?
If the fading in the UI is really the cause, then I don't know how it could be optimized further. I use CSS standards here

**Comment by goldyfruit** [comment]
Hey @jalibu, thanks for your answer.
I'm not using any browser but the directly starting MagicMirror as an application.

I'll retry with a lower `fading` value.

**Comment by jalibu** [comment]
are you using the docker images of khassel?

**Comment by goldyfruit** [comment]
> are you using the docker images of khassel?

Yes I do.

**Comment by jalibu** [comment]
Unfortunately I don’t have time to test that at the moment, as I am not using Docker for MM.
As of https://github.com/jalibu/MMM-RAIN-MAP/issues/25 I know, that a misconfiguration can cause problems with some modules with higher GPU usage.

**Comment by goldyfruit** [comment]
Just as information, here is a graph that demonstrates the CPU consumption:

![image](https://user-images.githubusercontent.com/614115/150348349-805ee07d-d6d3-4db9-aff9-4e5fdf26fd2b.png)

**Comment by jalibu** [comment]
@goldyfruit please let me know if there is something I can optimise in the module. As said, the module only uses CSS standards and high CPU consumption does not seem to be a general problem with that module.

Feel free to re-open this ticket once you have more insights/solutions/ideas.

Thank you for your feedback.
