### ISSUE TITLE
Stuttering horizontal scrolling on Raspberry Pi 4 (2GB)

### ISSUE THREAD

**Issue by MichlF** [jalibu/MMM-Jast#37]
### Platform

Raspberry Pi OS

### Node.js Version

16.13.2

### MagicMirror Version

2.17.1

### Module Version

most recent (v2.6.2.)

### Description

Horizontal scrolling is choppy / stuttering / lagging. No consistent pattern observable and no relief after running longer. No relief when removing other modules either. MagicMirror does not run in a docker.

### Expected behavior

Should run smoothly

### Current behavior

Runs choppy / stutters / lags

### Possible solution

A RAM problem? Maybe 2 GB RAM is too low?

### Steps to reproduce

Simply start the application.

### Log

```shell
No errors
```

### config.js

```javascript
{
			module: "MMM-Jast",
			position: "bottom_bar",
			config: {
				maxWidth: "100%",
				updateIntervalInSeconds: 300,
				fadeSpeedInSeconds: 40,
				scroll: "horizontal", // One of ["none", "vertical", "horizontal"]
				useGrouping: false,
				currencyStyle: "symbol", // One of ["code", "symbol", "name"]
				lastUpdateFormat: "HH:mm",
				showColors: true,
				showCurrency: true,
				showChangePercent: true,
				showChangeValue: false,
				showChangeValueCurrency: false,
				showLastUpdate: false,
				showPortfolioValue: false,
				showPortfolioGrowthPercent: false,
				showPortfolioGrowth: false,
				numberDecimalsValues: 2,
				numberDecimalsPercentages: 1,
				virtualHorizontalMultiplier: 1,
				stocks: [
					{ name: "iShares Global Clean Energy", symbol: "IQQH.DE"},
					{ name: "iShares Core MSCI World", symbol: "EUNL.DE" },
					{ name: "iShares Core MSCI EM IMI", symbol: "IS3N.DE"},
					{ name: "iShares MSCI World Small Cap", symbol: "IUSN.DE"},
				]
			}
		},
```

**Comment by jalibu** [comment]
Hi @MichlF ,
yes, 2GB is too low, I guess.

The horizontal scrolling uses CSS3 fading standards only. I'm afraid there is nothing I can optimise here.

**Comment by jalibu** [comment]
PS: I run it together with other GPU rendering intensive modules (MMM-Rain-Map) on a Raspi4 4GB without problems.

**Comment by MichlF** [comment]
Aight well. 4gigs+ Pis are just so expensive right now that I cannot really test it using the same environment. But when I have the time/money and the issue persists because of something else than hardware, I can reopen the issue.
