### ISSUE TITLE
Update Procedure

### ISSUE THREAD

**Issue by ankonaskiff17** [jalibu/MMM-Jast#41]
This morning I woke up and MM was saying there is an update for MMM-Jast which I assume is due to this dependency being updated. What do I need to do to clear the notification?
![dependency](https://user-images.githubusercontent.com/52932685/168895006-8eef08d8-80ac-4f7e-822d-06839e856933.jpg)

**Comment by jalibu** [comment]
on your MM, navigate into the module folder, e.g. `/home/pi/MagicMirror/modules/MMM-Jast` and execute `git pull`
if that command fails with a message that there is some conflict with package-lock.json, then execute `git checkout package-lock.json` first

**Comment by ankonaskiff17** [comment]
Sam got me straight. I knew some modules had a section in readme about updating so did same.Had package-lock issue but everything is back to normal.Wayne Wells
-------- Original message --------From: Jan ***@***.***> Date: 5/18/22  3:38 AM  (GMT-05:00) To: jalibu/MMM-Jast ***@***.***> Cc: ankonaskiff17 ***@***.***>, Author ***@***.***> Subject: Re: [jalibu/MMM-Jast] Update Procedure (Issue #41) 
on your MM, navigate into the module folder, e.g. /home/pi/MagicMirror/modules/MMM-Jast and execute git pull
if that command fails with a message that there is some conflict with package-lock.json, then execute git checkout package-lock.json first
