### ISSUE TITLE
Show change only during weekdays?

### ISSUE THREAD

**Issue by Qwarkk6** [jalibu/MMM-Jast#43]
I love the module, just wondering if it would be possible to add a feature where the percentage change in stock value is only visible during weekdays and not on weekends.

**Comment by jalibu** [comment]
@Qwarkk6 what do you think about an option, that checks the last change age and ignores it if it is older than 24h?

**Comment by jalibu** [comment]
@Qwarkk6 please checkout the `development` branch

**Comment by jalibu** [comment]
fixed

**Comment by Qwarkk6** [comment]
Sorry, haven't been active on here for some time. Thank you for taking a look at this.
