### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by AlienPT** [jalibu/MMM-Jast#45]
Hi,
I have this plugin and all worked fine for long time.
Nothing has been changed on my end and now it's still just "Loading..."
Any advise?
Thank you

Pavol

**Comment by jalibu** [comment]
Hi @AlienPT , please open a Bug Report Issue and add all required information to debug your problem

**Comment by AlienPT** [comment]
Hi @jalibu,
just FYI...
after I deleted and reinstalled your package all is working again.

Pavol
