### ISSUE TITLE
Module stuck on “Loading” PLEASE HELP!!!

### ISSUE THREAD

**Issue by jfc0316** [jalibu/MMM-Jast#46]
Hey everyone! I need some help on this one. It’s been a while since I’ve had any issues with my magic mirror until very recently when I noticed that my stocks (MMM-Jast) module was stuck on “loading.” I’ve tried uninstalling and reinstalling the module as well as reboot the pi as well. No dice. After further investigation I looked at the logs and noticed a few things. Before going any further please note the picture below that shows the module actually functioning. Out of the 10 stocks shown, the first 7 are cryptocurrencies. Now, when you look at the logs you’ll see ERROR: there was an error requesting the API. Failed yahoo schema validation. They all appear to be from “coinmarketcaplink” which would point to crypto as well. Troubleshooting along this line of thinking I removed all seven of the crypto currencies from the confect that JS file and just left apple, Tesla and AMC. Still stuck on loading so now I’m thinking it’s not crypto based?! How does one change the yahoo API if it changed or what else do you guys and girls think it could be!? 

![C1E2A4AE-A231-4AC6-8342-3840AE7D7497](https://user-images.githubusercontent.com/90428527/177418585-10c2d80e-7cb5-4af7-b886-2b7ee64c446f.jpeg)
![5FDBA653-FFF4-4051-B5DF-E722E0AE987F](https://user-images.githubusercontent.com/90428527/177418590-79c98727-3378-4292-a01b-0c6f028478e9.jpeg)
![354239C7-4404-4A6D-AFF9-AB0A05A5CF74](https://user-images.githubusercontent.com/90428527/177418591-914eb85a-40c5-43d9-b54d-6d6708a212a9.jpeg)
![CE419D31-24E4-46A9-A69A-428B7808DBA4](https://user-images.githubusercontent.com/90428527/177418594-77c4d440-d9d9-4fce-869b-574bf8ef4e91.jpeg)
![C04BEF63-A9E7-4C22-9F76-33870EDC3BB1](https://user-images.githubusercontent.com/90428527/177418595-b6584bb6-d31b-40c3-a695-0a225304930b.jpeg)
![3D3AE68A-BC51-46E2-9FAA-B5EE89A482E5](https://user-images.githubusercontent.com/90428527/177418597-49f40059-388d-4f77-8914-312c2cbcd1bb.jpeg)

**Comment by jalibu** [comment]
This perfectly works on my end
```
{
			module: "MMM-Jast",
			position: "top_left",
			config: {
				stocks: [
					{ name: "TESTLA", symbol: "TSLA" },
					{ name: "APPLE", symbol: "AAPL" },
					{ name: "AMC", symbol: "AMC" }
				],
				fadeSpeedInSeconds: 35,
				scroll: "none",
				showHiddenStocks: true,
				showChangeValue: true
			}
		}
```

<img width="394" alt="image" src="https://user-images.githubusercontent.com/25933231/177490328-57ba4d90-fd2d-45e9-83a7-fc29f186a597.png">

**Comment by jalibu** [comment]
Why did you open the issue as a feature request? To help you here, I need the information that is requested in the bug issue template. How else am I supposed to know what version of Jast (and thus Yahoo Dependencies) you have? ;-)
It's also pretty hard to type out your config from a screenshot to debug your problem.
