### ISSUE TITLE
Module stuck on "LOADING"

### ISSUE THREAD

**Issue by jfc0316** [jalibu/MMM-Jast#47]
### Platform

Raspberry Pi OS

### Node.js Version

12.22.0

### MagicMirror Version

2.16.0

### Module Version

b6721cda613e07db6b3933cfc872d396a0c391ab

### Description

Accidentally opened issue under feature request.
Module never loads and once MagicMirror starts all I typically see is "loading"
I’ve tried uninstalling and reinstalling the module as well as reboot the pi as well. No dice. After further investigation I looked at the logs and noticed a few things. Before going any further please note the picture below that shows the module actually functioning. Out of the 10 stocks shown, the first 7 are cryptocurrencies. Now, when you look at the logs you’ll see ERROR: there was an error requesting the API. Failed yahoo schema validation. They all appear to be from “coinmarketcaplink” which would point to crypto as well. Troubleshooting along this line of thinking I removed all seven of the crypto currencies from the confect that JS file and just left apple, Tesla and AMC. Still stuck on loading so now I’m thinking it’s not crypto based?! How does one change the yahoo API? Just thinking out load. It's probably something silly that needs updating but I have almost 12 + other modules and this is the only non working one?

### Expected behavior

The stocks should load accordingly!

### Current behavior

"LOADING"

### Steps to reproduce

Please see above 

### Log

```shell
16.07.2022 16:59.29.931] [LOG]   
This may happen intermittently and you should catch errors appropriately.
However:  1) if this recently started happening on every request for a symbol
that used to work, Yahoo may have changed their API.  2) If this happens on
every request for a symbol you've never used before, but not for other
symbols, you've found an edge-case.  Please see if anyone has reported
this previously:

  [object Object]/issues?q=is%3Aissue+Failed%20validation%3A%20%23%2Fdefinitions%2FQuoteSummaryResult

or open a new issue (and mention the symbol):

  [object Object]/issues/new?title=Failed%20validation%3A%20%23%2Fdefinitions%2FQuoteSummaryResult

For information on how to turn off the above logging or skip these errors,
see https://github.com/gadicc/node-yahoo-finance2/tree/devel/docs/validation.md.

[16.07.2022 16:59.29.933] [ERROR] There was an error requesting the API. Failed Yahoo Schema validation
[16.07.2022 16:59.30.262] [LOG]   The following result did not validate with schema: #/definitions/QuoteSummaryResult
[
  {
    keyword: 'additionalProperties',
    dataPath: '/summaryDetail',
    schemaPath: '#/definitions/SummaryDetail/additionalProperties',
    params: { additionalProperty: 'coinMarketCapLink' },
    message: 'should NOT have additional properties',
```

### config.js

```javascript
{
			module: "MMM-Jast",
			position: "bottom_left",
			config: {
			maxWidth: "100%",
			updateIntervalInSeconds: 300,
			fadeSpeedInSeconds: 3.5, // Higher value: vertical -> faster // horizontal -> slower
			scroll: "none", // One of ["none", "vertical", "horizontal"]
			useGrouping: false,
			currencyStyle: "code", // One of ["code", "symbol", "name"]
			showColors: true,
			showCurrency: true,
			showChangePercent: true,
			showChangeValue: false,
			showChangeValueCurrency: false,
			showPortfolioValue: false,
			showPortfolioGrowthPercent: false,
			showPortfolioGrowth: false,
			numberDecimalsValues: 6,
			numberDecimalsPercentages: 1,
			virtualHorizontalMultiplier: 2,
			stocks: [
                               	{ name: "BITCOIN", symbol: "BTC" },
 				{ name: "ETHEREUM", symbol: "ETH" },
				{ name: "CARDANO", symbol: "ADA-USD" },
				{ name: "DOGE", symbol: "DOGE-USD" },
				{ name: "SHIBA INU", symbol: "SHIB-USD" },
				{ name: "VECHAIN", symbol: "VET-USD" },
				{ name: "STELLAR", symbol: "XLM-USD" },
				{ name: "AMC", symbol: "AMC" },
				{ name: "TESLA", symbol: "TSLA" },
				{ name: "APPLE", symbol: "AAPL" },
		]
		}
		}
		]
		};
```

### Additional info

PLEASE HELP!!!

**Comment by jalibu** [comment]
Please update the module to the latest version. Your's is more than 1 year old.
Except of ETH, there are no problems with this config on my side.

**Comment by jfc0316** [comment]
“npm run update”? 
I think I tried that and it failed.
How do you update???

Jason Cox

**Comment by jfc0316** [comment]
Jan, 

Thanks so much again for the quick response!  Both of those commands failed and I kept getting a "your configuration specifies to merge with the ref ref/heads/master from the remote but no such ref was fetched. When I ran the git reset hard pull I did get "HEAD" is now b6721cd update README.md and then the same ""your configuration specifies to merge with the ref ref/heads/master from the remote but no such ref was fetched" again. 

I tried the following:

git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a

and then up course did the "git pull" then reinstalled dependencies with npm.
launched the Mirror and everything loaded ... ALMOST!!!! 

Out of the 10 stocks that I've got displayed, 9 of them load!!?!? 
ETH - Ethereum, is the only one that does not load. 
Didn't you say that you had an issue with ETH as well from above???

Why do you think that one isn't working?

**Comment by jfc0316** [comment]
FIGURED IT OUT ... 

I'm not sure why, probably yahoo but I changed the config.js file from "ETH" to "ETH-USD" and it loaded! Bitcoin was previously loading as well but the price was incorrect so I did the same with BTC-USD and it too is now displaying properly! Issue resolved my friend! thank you again!
