### ISSUE TITLE
Module not centered

### ISSUE THREAD

**Issue by goldyfruit** [jalibu/MMM-Jast#50]
### Platform

Raspberry PI OS Bullseye 64bit

### Node.js Version

17.6.0

### MagicMirror Version

2.19.0

### Module Version

1cc458d

### Description

When only one stock is configured the module is not centered, with four stocks configured, every things is centered.

### Steps to reproduce

- Configure one stock only (not centered)
- Configure two stocks only (not centered)
- Configure three stocks only (not centered)
- Configure fours stocks only (centered)

### config.js

```javascript
{
            module: 'MMM-Jast',
            disabled: false,
            position: 'bottom_bar',
            header: '',
            config: {
                fadeSpeedInSeconds: 3.5,
                updateIntervalInSeconds: 600,
                scroll: 'horizontal',
                stocks: [
                    {
                        name: 'Alibaba',
                        symbol: 'BABA'
                    }
                ]
            }
        }
```

### Additional info

![image](https://user-images.githubusercontent.com/614115/194731217-5ffe5a86-5831-403e-91ab-8352f8c08329.png)

![image](https://user-images.githubusercontent.com/614115/194731345-e8ac2d7c-329d-43ce-9dd9-0e5468259ed6.png)

![image](https://user-images.githubusercontent.com/614115/194731353-84d4e5f6-f6db-42df-b696-ded98562b1c1.png)

**Comment by jalibu** [comment]
hi @goldyfruit have you tried with scrolling: 'none' option?

**Comment by goldyfruit** [comment]
@jalibu `none` kind of works but I guess it could me more compact.

![image](https://user-images.githubusercontent.com/614115/194758424-ff7dad1b-a32e-4a0e-a671-a2c54898dd57.png)

Thanks!

**Comment by goldyfruit** [comment]
By switching to `vertical` with one stock, it centered.

![image](https://user-images.githubusercontent.com/614115/194760998-12dd86f2-f059-43df-8bb2-a9876cbbddfb.png)
