### ISSUE TITLE
Ignoring decimal places parameters.

### ISSUE THREAD

**Issue by BillYovino** [jalibu/MMM-Jast#55]
### Platform

Raspberry Pi OS Bullseye 64

### Node.js Version

16.20.0

### MagicMirror Version

2.23

### Module Version

v2.80

### Description

The module is ignoring the config values for **numberDecimalsPercentages** and **numberDecimalsValues**
Regardless of the settings, the stock values and change percentages are showing 3 decimal places.

![MMM-Jast Screenshot](https://github.com/jalibu/MMM-Jast/assets/58706002/34aa1d35-2cf4-4920-9d71-386a986baf04)

### Expected behavior

I would expect AMZN to show as 124..86 (-0.93) and UA as 6.83 (-0.10)

### Current behavior

 AMZN shows as 124..855 (-0.925) and UA as 6.825 (-0.0985)

### Possible solution

I believe the module is ignoring the config values and defaults for those attributes.

### Steps to reproduce

The issue is constant and repeatable.

### Log

```shell
No errors, just incorrect formatting
```

### config.js

```javascript
{
	module: "MMM-Jast",
	position: "bottom_bar",
	config: {
		currencyStyle: "code", // One of ["code", "symbol", "name"]
		fadeSpeedInSeconds: 100,
		lastUpdateFormat: "HH:mm",
		maxChangeAge: 1 * 24 * 60 * 60 * 1000,
		maxWidth: "100%",
		numberDecimalsPercentages: 1,
		numberDecimalsValues: 2,
		scroll: "horizontal", // One of ["none", "vertical", "horizontal"]
		showColors: true,
		showCurrency: false,
		showChangePercent: false,
		showChangeValue: true,
		showChangeValueCurrency: false,
		showHiddenStocks: false,
		showLastUpdate: false,
		showPortfolioValue: false,
		showPortfolioGrowthPercent: false,
		showPortfolioGrowth: false,
		updateIntervalInSeconds: 300,
		useGrouping: false,
		virtualHorizontalMultiplier: 2,
		stocks: [
			{ name: "DJI", symbol: "^DJI"},
			{ name: "NASD", symbol: "^IXIC"},
			{ name: "AAPL", symbol: "AAPL" },
			{ name: "GOOG", symbol: "GOOG"},
                        { name: "AMZN", symbol: "AMZN"},
                        { name: "META", symbol: "META"},
                        { name: "TSLA", symbol: "TSLA"},
                        { name: "UA", symbol: "UA"}
		]
	}
}
```

**Comment by jalibu** [comment]
Hi @BillYovino ,

thank you for reporting this.

I can reproduce your finding. I'll try to fix it asap

**Comment by jalibu** [comment]
Should be fixed with https://github.com/jalibu/MMM-Jast/releases/tag/v2.8.2

**Comment by BillYovino** [comment]
Thanks! That was quick. Do I git clone the repository again or is there
another way to update it?
