### ISSUE TITLE
Invalid Cookie

### ISSUE THREAD

**Issue by dushyantahuja** [jalibu/MMM-Jast#56]
### Platform

Docker

### Node.js Version

v18.16.1

### MagicMirror Version

2.24.0

### Module Version

v2.8.0

### Description

Since the last few days, I'm getting the following error, and the module is stuck at 'Loading':

[WARN]  API request for ETH-INR failed: Invalid Cookie

config.js has the following:

{
        module: "MMM-Jast",
        position: "top_right",
        config: {
            currencyStyle: "code", // One of ["code", "symbol", "name"]
            fadeSpeedInSeconds: 350,
            lastUpdateFormat: "HH:mm",
            maxChangeAge: 1 * 24 * 60 * 60 * 1000,
            maxWidth: "100%",
            numberDecimalsPercentages: 0,
            numberDecimalsValues: 0,
            scroll: "none", // One of ["none", "vertical", "horizontal"]
            showColors: true,
            showCurrency: false,
            showChangePercent: true,
            showChangeValue: false,
            showChangeValueCurrency: false,
            showHiddenStocks: false,
            showLastUpdate: false,
            showPortfolioValue: false,
            showPortfolioGrowthPercent: false,
            showPortfolioGrowth: false,
            updateIntervalInSeconds: 300,
            useGrouping: true,
            virtualHorizontalMultiplier: 2,
            stocks: [
                { name: "ETH", symbol: "ETH-INR", quantity: 1 },
                {name: "NIFTY 50", symbol:"^NSEI"},
                { name: "NIFTY BeES", symbol: "NIFTYBEES.NS" },
                { name: "USD", symbol: "INR=X" },
                { name: "VOO - US", symbol: "VOO"},
            ]
        }
    },

### Steps to reproduce

1. Start MM
2. Module gets stuck

### config.js

```javascript
{
        module: "MMM-Jast",
        position: "top_right",
        config: {
            currencyStyle: "code", // One of ["code", "symbol", "name"]
            fadeSpeedInSeconds: 350,
            lastUpdateFormat: "HH:mm",
            maxChangeAge: 1 * 24 * 60 * 60 * 1000,
            maxWidth: "100%",
            numberDecimalsPercentages: 0,
            numberDecimalsValues: 0,
            scroll: "none", // One of ["none", "vertical", "horizontal"]
            showColors: true,
            showCurrency: false,
            showChangePercent: true,
            showChangeValue: false,
            showChangeValueCurrency: false,
            showHiddenStocks: false,
            showLastUpdate: false,
            showPortfolioValue: false,
            showPortfolioGrowthPercent: false,
            showPortfolioGrowth: false,
            updateIntervalInSeconds: 300,
            useGrouping: true,
            virtualHorizontalMultiplier: 2,
            stocks: [
                { name: "ETH", symbol: "ETH-INR", quantity: 1 },
                {name: "NIFTY 50", symbol:"^NSEI"},
                { name: "NIFTY BeES", symbol: "NIFTYBEES.NS" },
                { name: "USD", symbol: "INR=X" },
                { name: "VOO - US", symbol: "VOO"},
            ]
        }
    },
```

**Comment by oturan233** [comment]
I have the same problem. I love this module, please fix it..

**Comment by packetchef** [comment]
+1

**Comment by jalibu** [comment]
Hi @packetchef @dushyantahuja @oturan233

This issue was fixed: https://github.com/jalibu/MMM-Jast/releases/tag/v2.8.1

You need to execute `npm i` in the MMM-Jast folder after pulling my changes, because an external dependency has been updated.

**Comment by dushyantahuja** [comment]
Thanks - works now; though I had to restart the docker before things started working.
