### ISSUE TITLE
Stocks not loading.

### ISSUE THREAD

**Issue by themox** [jalibu/MMM-Jast#59]
### Platform

Ubuntu 20.04

### Node.js Version

v16.14.0

### MagicMirror Version

2.24.0

### Module Version

V2.6.2

### Description

Jast won't load.  Simply says, "loading..."  Error log reflects the following error message for all stocks in list to load (ASTR in this case is an example stock).

[WARN]  API request for ASTR failed: Invalid Cookie

### Expected behavior

Stocks should load & display

### Current behavior

Stocks aren't loading.

### Possible solution

Haven't had a chance to troubleshoot, I suspect it is an API issue.

### Steps to reproduce

1. Start MM.

### Log

```shell
see above.
```

### config.js

```javascript
{
	module: "MMM-Jast",
	position: "top_right",
	config: {
		maxWidth: "100%",
		updateIntervalInSeconds: 300,
		fadeSpeedInSeconds: 3.5,
		scroll: "none", // One of ["none", "vertical", "horizontal"]
		useGrouping: false,
		currencyStyle: "code", // One of ["code", "symbol", "name"]
		lastUpdateFormat: "HH:mm",
		showColors: true,
		showCurrency: false,
		showChangePercent: true,
		showChangeValue: false,
		showChangeValueCurrency: false,
		showLastUpdate: true,
		showPortfolioValue: true,
		showPortfolioGrowthPercent: false,
		showPortfolioGrowth: true,
		numberDecimalsValues: 2,
		numberDecimalsPercentages: 1,
		virtualHorizontalMultiplier: 2,
		stocks: [
   			{ name: "Astra Space", symbol: "ASTR", quantity: 1},
		]

	}
},// end MMM-Jast stock ticker
```

### Additional info

No additional info

**Comment by jalibu** [comment]
Update to latest module version and execute `npm i` from within the module's directory.

**Comment by themox** [comment]
Great, thanks!
