### ISSUE TITLE
Support Custom Formatting

### ISSUE THREAD

**Issue by themox** [jalibu/MMM-Jast#65]
The last few updates have broken my formatting using custom CSS.  The current default alignment in vertical mode aligns all text to the left.  I am looking for something more "accounting style" where the numbers on the right are all aligned vertically with the colons on the left also aligned.

A simple way to allow folks to customize their alignment would be to assign and publish unique class names to each of the spans (many currently are not assigned classes).

I've tried a number of ways to format with the current update, but because of how the spans are nested and classed (or not classed), I am unable to get there.

As I inspect the html, I see something like the following:

```
<li class="jast-stock">
<span>NVIDIA:</span>
<span class="high">
<span>490.97</span>
"("
<span class="jast-change-value">+2.3%</span>
")"
</span>
</span>
<span class> </span>
</li>
```

So the span with the stock name and stock price have no class.  And you can see a weird span at the bottom that appears to be an error, with a partial class label.  Perhaps something like "jast-stock-name" and "jast-stock-price".  Thanks!

**Comment by jalibu** [comment]
Hi @themox,
thank you for your input.

I will take a look at this soon

**Comment by jalibu** [comment]
@themox done. Please provide feedback

**Comment by themox** [comment]
@jalibu Thank you for your patience on the feedback.  I appreciate the update.  This is really close.  Most of the list can be styled perfectly.  The only thing I would add would be to enclose the last part as well in individual tags (where the summation is or total portfolio value).  For example, right now you have something like (this is very rough but just to give you the idea):

<li>Portfolio <span>$1000.00<span>+10%</span></span></li>

The pieces are all embedded within each other so you cannot style them individually.  If you do something similar to the rest of the list-items where they can be embedded but each piece is also individually tagged with a class or label.  The summary is also different than an individual stock list-item, so should be labeled differently.

I do not mean to be difficult.  I really enjoy your module and it is the best of the ones I have tried.  Thank you for bearing with me!

**Comment by jalibu** [comment]
ok. I can probably adjust that tomorrow.

Is it worth sharing your custom styles for others?

**Comment by themox** [comment]
Happy to do so; once we finish this up I'll post my final here and if you want to put it somewhere more visible for others you can.

**Comment by jalibu** [comment]
@themox I added a few more classes.

If you have more specific wishes, please give me a concrete and clearly localizable example like

Now
`<li>Bla</li>`

Request
`<li class="jast-bla">Bla</li>`
