### ISSUE TITLE
Scrolling not over full screen

### ISSUE THREAD

**Issue by Mincerlicious** [jalibu/MMM-Jast#7]
Hello,

the module is great! Unfortunately i can't get it to scroll across the full screen. It just stops at around a third of the screen. Sometimes it's aligned right, sometimes it's aligned left. Max width doesn't change that.

Fix would be appreciated, because it's the only stock module that supports EUR stocks as well.

Kind regards

**Comment by jalibu** [comment]
Should be fixed with the latest version.
Please check @Mincerlicious

**Comment by jalibu** [comment]
@Mincerlicious please feel free to open a new issue if the problem still exists. Thank you for your support.
